application: hazlorisk
version: 1
runtime: python
api_version: 1

default_expiration: "30m"

handlers:
- url: /stylesheet
  static_dir: stylesheet

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: main.py
  login: admin